import { Request, Response } from "express";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Get all students
export const getAllStudents = async (req: Request, res: Response) => {
  try {
    const students = await prisma.student.findMany({
    
      include: { parent: true, class: true, Subject: true },
    });
    res.json(students);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch students" });
  }
};

// Get a student by ID
export const getStudentById = async (req: Request, res: Response) : Promise<void>=> {
  const { id } = req.params;
  try {
    const student = await prisma.student.findUnique({
      where: { id },
      include: { parent: true, class: true,Subject:true},
    });
    if (!student) {
       res.status(404).json({ error: "Student not found" });
       return
    }
    res.json(student);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch student" });
  }
};

// Create a new student

const normalizeForUsername = (value: string): string =>
  value.trim().toLowerCase().replace(/[^a-z0-9]/g, "");

type ParentResolution = { ok: true; parentId: string | null } | { ok: false };

// Resolve a parent for a student: link an existing one by id, find-or-create by
// phone (so siblings automatically link to the same parent instead of
// duplicating), or none. On failure, writes the response itself (ok: false) -
// callers should just `return` when they see ok: false.
const resolveParentId = async (
  parentId: string | null | undefined,
  parentInput: any,
  res: Response
): Promise<ParentResolution> => {
  if (parentId) {
    const existingParent = await prisma.parent.findUnique({ where: { id: parentId } });
    if (!existingParent) {
      res.status(404).json({ error: "Parent not found" });
      return { ok: false };
    }
    return { ok: true, parentId: existingParent.id };
  }

  if (parentInput) {
    const { name: parentName, surname: parentSurname, phone: parentPhone, email: parentEmail, address: parentAddress } = parentInput;
    if (!parentName || !parentSurname || !parentPhone || !parentAddress) {
      res.status(400).json({ error: "parent.name, parent.surname, parent.phone and parent.address are required to create a new parent." });
      return { ok: false };
    }

    const existingParentByPhone = await prisma.parent.findUnique({ where: { phone: parentPhone } });
    if (existingParentByPhone) {
      // Same parent already on file (e.g. a sibling already enrolled) - link to them, don't duplicate.
      return { ok: true, parentId: existingParentByPhone.id };
    }

    const parentUsername = `${normalizeForUsername(parentName)}.${normalizeForUsername(parentSurname)}.enfedamacademy`;
    const existingParentByUsername = await prisma.parent.findUnique({ where: { username: parentUsername } });
    if (existingParentByUsername) {
      res.status(400).json({
        error: "A different parent with this same name already exists (different phone number). Please double-check the phone number, or contact support to resolve the naming conflict.",
      });
      return { ok: false };
    }

    const newParent = await prisma.parent.create({
      data: {
        id: crypto.randomUUID(),
        username: parentUsername,
        name: parentName,
        surname: parentSurname,
        phone: parentPhone,
        email: parentEmail || null,
        address: parentAddress,
      },
    });
    return { ok: true, parentId: newParent.id };
  }

  return { ok: true, parentId: null };
};

export const createStudent = async (
  req: Request,
  res: Response
): Promise<void> => {
  const {
    username: requestedUsername,
    name,
    surname,
    email,
    phone,
    address,
    img,
    bloodType,
    sex,
    parentId = null,
    parent: parentInput,
    classId,
    birthday,
    subjectIds = [],
  } = req.body;

  try {
    if (!name || !surname) {
      res.status(400).json({ error: "name and surname are required" });
      return;
    }

    // Auto-generate the username (firstname.surname.enfedamacademy) when none is supplied.
    const isAutoGenerated = !requestedUsername;
    const username = requestedUsername || `${normalizeForUsername(name)}.${normalizeForUsername(surname)}.enfedamacademy`;

    // Check if the username already exists
    const existingStudent = await prisma.student.findUnique({
      where: { username },
    });

    if (existingStudent) {
      res.status(400).json({
        error: isAutoGenerated
          ? "A username could not be auto-generated: a student with this full name already exists. Please provide a username manually."
          : "Student with this username already exists",
      });
      return;
    }

    // Validate birthday format
    const parsedBirthday = new Date(birthday);
    if (isNaN(parsedBirthday.getTime())) {
      res.status(400).json({ error: "Invalid birthday format" });
      return;
    }

    // Validate if classId exists
    let classData = null;
    if (classId) {
      classData = await prisma.class.findUnique({ where: { id: classId } });
      if (!classData) {
        res.status(404).json({ error: "Class not found" });
        return;
      }
    }

    // Resolve the parent: link an existing one by id, find-or-create by phone, or none.
    const parentResolution = await resolveParentId(parentId, parentInput, res);
    if (!parentResolution.ok) return;
    const resolvedParentId = parentResolution.parentId;

    // Validate subjects
    const validSubjectIds = await prisma.subject.findMany({
      where: {
        id: { in: subjectIds },
      },
      select: { id: true },
    });

    if (validSubjectIds.length !== subjectIds.length) {
      res.status(400).json({ error: "Some subjectIds are invalid" });
      return;
    }

    const studentData: any = {
      id: crypto.randomUUID(),
      username,
      name,
      surname,
      email: email || null,
      phone: phone || null,
      address,
      img: img || null,
      bloodType,
      sex: sex.toUpperCase(),
      birthday: parsedBirthday,
      Subject: {
        connect: validSubjectIds.map((s:any) => ({ id: s.id })), // ✅ connect subjects
      },
    };

    if (resolvedParentId) studentData.parent = { connect: { id: resolvedParentId } };
    if (classData) studentData.class = { connect: { id: classId } };

    const student = await prisma.student.create({
      data: studentData,
      include: { Subject: true, class: true, parent: true },
    });

    res.status(201).json(student);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to create student" });
  }
};


// Update a student
export const updateStudent = async (req: Request, res: Response): Promise<void> => {
  const { id } = req.params;
  const {
    username,
    name,
    surname,
    email,
    phone,
    address,
    img,
    bloodType,
    sex,
    parentId,
    parent: parentInput,
    classId,
    birthday,
  } = req.body;
  try {
    let resolvedParentId: string | null | undefined = parentId;
    if (parentId || parentInput) {
      const parentResolution = await resolveParentId(parentId, parentInput, res);
      if (!parentResolution.ok) return;
      resolvedParentId = parentResolution.parentId;
    }

    const student = await prisma.student.update({
      where: { id },
      data: {
        username,
        name,
        surname,
        email,
        phone,
        address,
        img,
        bloodType,
        sex,
        parentId: resolvedParentId,
        classId,
        birthday,
      },
      include: { parent: true, class: true },
    });
    res.json(student);
  } catch (error) {
    console.error(error);
    res.status(400).json({ error: "Failed to update student" });
  }
};

// Delete a student
export const deleteStudent = async (req: Request, res: Response) => {
  const { id } = req.params;
  try {
    await prisma.student.delete({ where: { id } });
    res.status(204).send();
  } catch (error) {
    res.status(400).json({ error: "Failed to delete student" });
  }
};
